### ISSUE TITLE
Generating Standoc documents

### ISSUE THREAD

**Issue by kickoke** [metanorma/mn-samples-standoc#1]
I'm currently creating a sample that I can use for the beginner tutorials for metanorma. 
The repository is based on the ISO rice model but is stripped down to just one document. 

I've changed :mn-document-class: to standoc, to indicate that I want to use the Standoc model.
Now, when I want to generate a file locally on my mac, it says:
`Error: loading gem `metanorma-standoc ` failed. Exiting.`

Do I need to install the flavor gems (in this case, vanilla) manually? 
Are there any other issues with publishing standoc documents at the moment? @opoudjis

**Comment by opoudjis** [comment]
Ok, so you've installed Metanorma, right? And compiled say ISO documents correctly? 

I can't replicate: when I add `:mn-document-class: standoc`, and run `bundle exec metanorma a.adoc`, I get complaints about other gems, but not that one:

````
bundle exec metanorma a.adoc
[metanorma] Error: flavor gem metanorma-iso not present
[metanorma] Error: flavor gem metanorma-iec not present
[metanorma] Error: flavor gem metanorma-bipm not present
[relaton] Info: detecting backends:
Metanorma XML Syntax: (XML Line 000015:13): element "copyright" incomplete; missing required element "owner"
Metanorma XML Syntax: (XML Line 000017:27): character content of element "doctype" invalid; must be equal to "document"
````

I'm not aware of any outstanding issues, and I'm going to do something brusque, and refer you to Manuel and Nermina :)

**Comment by opoudjis** [comment]
Update from @ronaldtse : metanorma a.adoc should work, metanorma site generate does not.

**Comment by kickoke** [comment]
> Update from @ronaldtse : metanorma a.adoc should work, metanorma site generate does not.

I've tried it both ways and get the same error. 
@opoudjis I've installed metanorma using homebrew. :)

**Comment by kickoke** [comment]
Status update @ronaldtse @opoudjis 
I'm getting the same kind of error when I try to compile the file using the latest metanorma docker image:

`kickoke@crispa standard % docker run -v "$(pwd)":/metanorma/ metanorma/metanorma metanorma compile document.adoc
/usr/local/bundle/gems/metanorma-ietf-2.3.6/lib/asciidoctor/ietf/converter.rb:123: warning: already initialized constant Asciidoctor::Ietf::Converter::BCP_KEYWORDS
/usr/local/bundle/gems/metanorma-ietf-2.3.6/lib/asciidoctor/ietf/cleanup.rb:11: warning: previous definition of BCP_KEYWORDS was here
[metanorma] Error: loading gem `metanorma-iso ` failed. Exiting.`


Maybe there is an error in the current install file?

**Comment by kickoke** [comment]
> Status update @ronaldtse @opoudjis
> I'm getting the same kind of error when I try to compile the file using the latest metanorma docker image:
> 
> `kickoke@crispa standard % docker run -v "$(pwd)":/metanorma/ metanorma/metanorma metanorma compile document.adoc /usr/local/bundle/gems/metanorma-ietf-2.3.6/lib/asciidoctor/ietf/converter.rb:123: warning: already initialized constant Asciidoctor::Ietf::Converter::BCP_KEYWORDS /usr/local/bundle/gems/metanorma-ietf-2.3.6/lib/asciidoctor/ietf/cleanup.rb:11: warning: previous definition of BCP_KEYWORDS was here [metanorma] Error: loading gem `metanorma-iso ` failed. Exiting.`
> 
> Maybe there is an error in the current install file?

Update: 

My bad, I didn't see that `:mn-document-class:` iso contained one whitespace after `iso`
🤦
